name: Print Success Message

on:
  push:
    branches:
      - master

jobs:
  success:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Print Success Message
        run: echo "Workflow ran successfully!"
